spring.application.name=user

server.port=8082

#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test
#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.show-sql=true

#spring.datasource.url=jdbc:postgresql://localhost:5432/userdb
#spring.datasource.username=jsingh
#spring.datasource.password=jsingh
#spring.jpa.database=POSTGRESQL
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.mongodb.uri=mongodb://localhost:27017/userdb
spring.mongodb.database=userdb