server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: jsingh
    password: jsingh
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect